project:
  title: "cognate-beginnings"
  type: website
  output-dir: docs
  
  preview: 
    port: 3333
    browser: true
    watch-inputs: false
    navigate: true
  
  render: 
    - index.qmd
    - docs/_repo-structure.qmd
    - docs/_repro.qmd
    - docs/_data-dictionary.qmd

thanks: |
  The authors declare no conflicts of interest with regard to the funding source of this study. This study was supported by the Spanish Ministry for Science and Innovation and State Research Agency (Project PID2021- 123416NB-I00 financed by MCIN/ AEI/ 10.13039/501100011033 / FEDER, UE) and the Economic and Social Research Council (ESRC) (ES/S010947/1, UK). GGC was supported by a FPI research contract (PRE2019-088165). DAV was supported by the European Union’s Horizon2020 research and innovation program under Marie Skłodowska–Curie Grant (765556) and partially supported by Portuguese national funds through the Foundation for Science and Technology, under project UIDB/00214/2020, awarded to the Center of Linguistics of the University of Lisbon. IC was supported by the Investigo program funded by the European Union’s NextGenerationEU (NGEU) recovery plan. NSG was supported by an ICREA Academia 2019 award from the Catalan Institution for Research and Advanced Studies (ICREA). We are grateful to Chiara Santolin, Ege E. Özer, and the rest of the Speech Acquisition and Perception research group, and to Alicia Franco-Martínez and Cristina Rodríguez-Prada, for their helpful feedback. We thank Xavier Mayoral, Silvia Blanch, and Cristina Cuadrado for their technical support, and Cristina Dominguez and Katia Pistrin for their efforts in recruiting infants. We also thank all families and infants who participated in the experiments. This study was conducted according to guidelines laid down in the Declaration of Helsinki, and was approved by the Drug Research Ethical Committee (CEIm) of the IMIM Parc de Salut Mar, reference 2020/9080/I. The data and code necessary to reproduce the analyses presented here are publicly accessible, as are the materials necessary to attempt to replicate the findings. The analyses presented here were not preregistered. Data, code, and materials for this research are available at the following URLs: https://osf.io/hy984/, https://github.com/gongcastro/cognate-beginnings.

execute:
  freeze: auto 

website:
  twitter-card:
    creator: "@gongcastro"
    site: "@cbcUPF"
    image: https://raw.githubusercontent.com/gongcastro/gongcastro.github.io/main/assets/media/favicon.ico
  favicon: https://raw.githubusercontent.com/gongcastro/gongcastro.github.io/main/assets/media/favicon.ico
  repo-url: https://github.com/gongcastro/cognate-beginnings
  repo-actions: [edit, issue]
  page-navigation: true
  
  navbar:
    pinned: true
    background: primary
    search: false
    left:
      - text: "Home"
        file: index.qmd
      - text: "Reproducibility"
        file: docs/_repro.qmd
      - text: "Data"
        file: docs/_data-dictionary.qmd
    right:
      - icon: github
        aria-label: github
        href: https://github.com/gongcastro/cognate-beginnings

  page-footer:
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub](https://github.com/gongcastro/cognate-beginnings)

format:
  html:
    shift-heading-level-by: 1
    theme: 
      - docs/_assets/style.scss
    toc: true
    toc-depth: 4
    retina: 3
    code-fold: true
    code-tools: true