---
author:
  - name: Gonzalo Garcia-Castro
    corresponding: true
    orcid: 0000-0002-8553-4209
    email: gonzalo.garciadecastro@upf.edu
    affiliations:
      - id: cbc
        name: Universitat Pompeu Fabra
        department: Center for Brain and Cognition
        address: Ramon Trias Fargas 25-27
        city: Barcelona
        region: Spain
        postal-code: "08005"
  - name: Daniela S. Avila-Varela
    orcid: 0000-0002-3518-8117
    affiliations: 
      - ref: cbc
  - name: Ignacio Castillejo
    orcid: 0000-0001-7445-0416
    affiliations: 
      - id: uam 
        name: Universidad Autónoma de Madrid
        department: Departamento de Psicología
        address: Iván Pavlov, 6
        city: Madrid
        region: Spain
        postal-code: "28049"
  - name: Nuria Sebastian-Galles
    orcid: 0000-0001-6938-2498
    affiliations: 
      - ref: cbc
keywords:
  - lexical acquisition
  - vocabulary
  - bilingualism
  - item response theory
  - bayesian
link-citations: true
editor: source
warning: false
error: false
format:
  html:
    theme: _assets/style.scss
    page-layout: article
    code-fold: true
    smooth-scroll: true
toc: true
fig-dpi: 1000
sidebar: true
---

```{r setup}
#| label: setup
#| message: false
#| warning: false
#| echo: false
# load objects -----------------------------------------------------------------
targets::tar_config_set(
  store = here::here("_targets"),
  script = here::here("_targets.R")
)

yaml_metadata <- rmarkdown::yaml_front_matter(
  here::here("manuscript", "manuscript.qmd")
)

title <- yaml_metadata$title
abstract <- yaml_metadata$abstract
thanks <- yaml_metadata$thanks

targets::tar_load(items)
targets::tar_load(participants)
targets::tar_load(responses)

library(dplyr)
library(tidyr)
library(knitr)

```


{{< include README.md >}}

## Abstract

`r abstract`

## Acknowledgements

The authors declare no conflicts of interest with regard to the funding source of this study. This study was supported by the Spanish Ministry for Science and Innovation and State Research Agency (Project PID2021- 123416NB-I00 financed by MCIN/ AEI/ 10.13039/501100011033 / FEDER, UE) and the Economic and Social Research Council (ESRC) (ES/S010947/1, UK). GGC was supported by a FPI research contract (PRE2019-088165). DAV was supported by the European Union’s Horizon2020 research and innovation program under Marie Skłodowska–Curie Grant (765556) and partially supported by Portuguese national funds through the Foundation for Science and Technology, under project UIDB/00214/2020, awarded to the Center of Linguistics of the University of Lisbon. IC was supported by the Investigo program funded by the European Union’s NextGenerationEU (NGEU) recovery plan. NSG was supported by an ICREA Academia 2019 award from the Catalan Institution for Research and Advanced Studies (ICREA). We are grateful to Chiara Santolin, Ege E. Özer, and the rest of the Speech Acquisition and Perception research group, and to Alicia Franco-Martínez and Cristina Rodríguez-Prada, for their helpful feedback. We thank Xavier Mayoral, Silvia Blanch, and Cristina Cuadrado for their technical support, and Cristina Dominguez and Katia Pistrin for their efforts in recruiting infants. We also thank all families and infants who participated in the experiments. This study was conducted according to guidelines laid down in the Declaration of Helsinki, and was approved by the Drug Research Ethical Committee (CEIm) of the IMIM Parc de Salut Mar, reference 2020/9080/I. The data and code necessary to reproduce the analyses presented here are publicly accessible, as are the materials necessary to attempt to replicate the findings. The analyses presented here were not preregistered. Data, code, and materials for this research are available at the following URLs: [https://osf.io/hy984/](https://osf.io/hy984/), [https://github.com/gongcastro/cognate-beginnings](https://github.com/gongcastro/cognate-beginnings).
