format:
  docx:
    reference-doc: _assets/template.docx
  arxiv-pdf:
    keep-tex: true  
    linenumbers: true
    doublespacing: false
    runninghead: "Cognate beginnings to bilingual lexical acquistion"
    include-in-header: 
      text: |
        \usepackage{tipa}
        \usepackage{booktabs}
    knitr:
      opts_chunk:
        dev: "cairo_pdf"
crossref:
  custom:
    - key: sfig
      kind: float
      reference-prefix: Figure SI
      space-before-numbering: false
    - key: stbl
      kind: float
      reference-prefix: Table SI
      space-before-numbering: false
editor: source
lang: en
freeze: true
echo: false
warning: false
message: false
prefer-html: true
fig-dpi: 1000
fig-align: center
linkcolor: black
link-citations: false
link-bibliography: false
always_allow_html: 'yes'
csl: _assets/apa7.csl
bibliography: _assets/references.bib
